language: python

python:
  - "3.6"

services:
  - postgresql

install:
  - pip install -r requirements/base.txt
  - pip install -r requirements/dev.txt

before_script:
  - psql -c 'create database devdb;' -U postgres

script:
  - pytest
  - pylama
