version: '3'

services:
  questor:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: questor_app
    ports:
      - 8000
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./questor:/app/questor/
      - ./supervisor:/app/supervisor/
    depends_on:
      - database
    network_mode: host
    environment:
      - ALLOWED_HOSTS
      - SECRET_KEY

  database:
    image: postgres
    container_name: questor_db
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB